
services:
    gin:
        build: ./backend
        container_name: api
        depends_on:
            - db
        networks:
            - app_net
        ports:
            - "8080:8080"
        environment:
            TZ: Europe/Moscow
    db:
        image: postgres:latest
        restart: always
        container_name: psql
        networks:
            - app_net
        ports:
            - "8081:5432"
        environment: 
            POSTGRES_PASSWORD: manager
            TZ: Europe/Moscow

    
    react-app:
        build: ./frontend
        container_name: frontend
        networks:
            - app_net
        ports:
           - "3000:3000"
        volumes:
            - ./frontend:/app
        depends_on:
            - gin
        environment:
            TZ: Europe/Moscow
    pinger:
        build: ./pinger
        networks:
            - app_net
        depends_on:
            - gin
        environment:
            TZ: Europe/Moscow
    
networks:
  app_net:
    name: "app_net"
    external: true

volumes:
  db:
    driver: local